# Generated by Django 3.0.6 on 2020-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('contentId', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('contentTypeId', models.IntegerField(default=-1)),
                ('readCount', models.IntegerField(default=0)),
                ('areaCode', models.IntegerField(default=-1)),
                ('sigunguCode', models.IntegerField(default=-1)),
                ('cat1', models.CharField(max_length=3)),
                ('cat2', models.CharField(max_length=6)),
                ('cat3', models.CharField(max_length=12)),
                ('mapX', models.CharField(max_length=20)),
                ('mapY', models.CharField(max_length=20)),
                ('mLevel', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('firstImage', models.CharField(max_length=100)),
                ('firstImage2', models.CharField(max_length=100)),
                ('homepage', models.CharField(max_length=400)),
                ('overview', models.TextField()),
                ('tel', models.CharField(max_length=20)),
                ('telName', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=50)),
                ('addr2', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(default='n', max_length=30)),
                ('areaId', models.IntegerField(default=-1)),
                ('count', models.IntegerField(default=0)),
                ('logTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(default='global', max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
            ],
        ),
    ]
