# Generated by Django 3.0.6 on 2020-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userRecommends',
            field=models.TextField(default=''),
        ),
    ]
